logo: The Delta School # add logo name
title: The Delta School Showcase
description: > # this means to ignore newlines until "baseurl:"
  Make. Discover. Grow.
permalink: ':title/'
baseurl: "/tds-symposium" # the subpath of your site, e.g. /blog
url: "https://cameronbuckleyastate.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: HomePage.mp4 # add banner video. Add your video file to the folder video
banner-title: High School Showcase # add banner title
banner-desc: 2020 Virtual Edition # add banner description

# Author settings
author-pic:  # your photo
author-name: # your name
about-author: # about author
email:  # your email
phone:  # your pnone number
website: https://www.thedeltaschool.org # you website

# Social link
google_url:    # add url link
twitter_url:  https://twitter.com/TheDeltaSchool  # add url link
instagram_url: https://www.instagram.com/thedeltaschool # add url link
pinterest_url: # add url link
dribbble_url:  # add url link
facebook_url: https://www.facebook.com/thedeltaschool # add url link

# Disqus
discus_identifier: thedeltaschool # add your discus identifier.  Not your username.  To get this, register your forum here with a unique ID: https://disqus.com/admin/create/

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 16
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-paginate
  - jekyll-sitemap

gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
